### ISSUE TITLE
Change the colors of the Stage 2 fairies shooting red orbs

### ISSUE THREAD

**Issue by Lyricana** [taisei-project/taisei#111]
-Technically by Ultroloth from his stream but I see it hasn't been pinned here.  

He wanted the colors changed to better reflect that they're separate from the lesser fairies and have more hp.

**Comment by Akaricchi** [comment]
Can't change the colors of enemies easily yet, but making the fairies recolorable as easily as the bullets are is probably a good idea for the future. I will just make those fairies use the BigFairy sprites for now.
