### ISSUE TITLE
Add sound effect when spell cards are low on health

### ISSUE THREAD

**Issue by Lyricana** [taisei-project/taisei#112]
Suggested by metsubou, who'd like to see a sound similar to the rumbling in Touhou when a spell or pattern is almost cleared.

**Comment by Akaricchi** [comment]
For what it's worth, there are actually 2 (or maybe even 3) distinct rumbling sounds in Touhou. One plays when you hit *anything*, the other if whatever you hit is on low health (and the 3rd, if I'm not imagining it, if it's on super-low health). That's definitely something I'd like to add eventually.
