### ISSUE TITLE
Compiling doesn't work

### ISSUE THREAD

**Issue by HybridDog** [taisei-project/taisei#117]
I'm using the latest version (master branch). When running ninja in the build folder, this error message appears:
```
[…]
Meson encountered an error:
Multiple producers for Ninja target "src/taisei@exe/core.c.o". Please rename your targets.
FAILED: build.ninja 
/usr/bin/python3 /usr/share/meson/meson --internal regenerate […]/taisei […]/taisei/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by lachs0r** [comment]
How old is your version of Meson? I think we might have broken compatibility with anything older than 0.45.0 or something.

**Comment by HybridDog** [comment]
I'm using version 0.42.1-1 (installed with apt).

**Comment by HybridDog** [comment]
I used version 0.42.1-1 (installed using apt on lubuntu 17.10).

I've installed version 0.45.1 now (using pip3 install meson) and uninstalled the old version. Compiling works now, thanks.
