### ISSUE TITLE
SDL_mixer is awful garbage that has to be replaced

### ISSUE THREAD

**Issue by Akaricchi** [taisei-project/taisei#126]
We can't time anything even remotely precisely with that garbage API, not to mention the random fucking clipping. See also https://discourse.libsdl.org/t/sdl-mixer-issue-no-one-talks-about/20200/2

This blocks #112 

At this point it might be reasonable to go back to OpenAL and see if we can synchronize the sfx timings nicely with it. There's also [this library](https://bitbucket.org/ewing/almixer) that's built around it that may or may not be suitable. It's also a good opportunity to refactor the audio code.

And I'm totally fucking not going to work on this shit.

**Comment by makise-homura** [comment]
Ah, well, I noticed some strange delays with using SDL_mixer+ALSA, which sometimes make deathbombing impossible. It looked like been resolved with SDL_mixer+Pulseaudio, but looks like problem is more wide than I expected.

**Comment by Akaricchi** [comment]
Closing a bunch of issues as stale and/or no longer relevant; feel free to reopen as needed.
