### ISSUE TITLE
Reimu A creates a small white line on the left side of the screen

### ISSUE THREAD

**Issue by Lyricana** [taisei-project/taisei#127]
![white line](https://user-images.githubusercontent.com/33564238/41197499-701e3466-6c26-11e8-928a-7390bffb235a.png)

**Comment by Akaricchi** [comment]
Haven't tackled this yet but I suspect this to be the cause: https://github.com/taisei-project/taisei/blob/eb6ee8587238dad42b6cace44d983b45a02932a3/src/stagedraw.c#L416

@laochailan wrote that originally so I'm pinging him. I'm not exactly sure what's going on there.
