### ISSUE TITLE
Weird jitters/lag happens at completely random intervals during play

### ISSUE THREAD

**Issue by Lyricana** [taisei-project/taisei#128]
Already discussed with Akari, however there is a lack of direction on what is causing it.

**Comment by Lyricana** [comment]
I've noticed this happening a lot less lately on the newer build so maybe it's not going to be as bad anymore.  (Though I still get momentary freezes while streaming sometimes.)

**Comment by Akaricchi** [comment]
Closing a bunch of issues as stale and/or no longer relevant; feel free to reopen as needed.
