### ISSUE TITLE
Spell Practice Mode for ToE Lasers Only

### ISSUE THREAD

**Issue by Lyricana** [taisei-project/taisei#134]
Suggested by Ultroloth.

**Comment by Akaricchi** [comment]
I'm not against this in principle, but I think that implementing special practice modes for cherry-picked sub-patterns is not the right approach. Something like that will eventually get quite messy both in the code and in the UI.

Something more general, such as a savestate system (perhaps in addition to cheats available in practice mode), could solve this -- then you'd be able to practice anything you want without us having to write any extra code to cover all the use-cases. It's non-trivial though. I'll investigate the feasibility of this once we start working on adding a scripting system.

**Comment by Akaricchi** [comment]
Closing a bunch of issues as stale and/or no longer relevant; feel free to reopen as needed.
