### ISSUE TITLE
Pressing the shot button cancels the stage-restart transition (e.g. from the ESC+R shortcut)

### ISSUE THREAD

**Issue by ultroloth** [taisei-project/taisei#136]
Tested in stage practice

**Comment by Akaricchi** [comment]
I can't reproduce this, and it's very unlikely that a death has anything to do with that at all - that code doesn't care about player state. The only caveat that I can think of is that the in-game menu still processes the input during the fade-out transition, so if you manage to hit Esc or the bomb key at that time, then the restart will be cancelled. The same thing will happen if you manually hit the "restart game" option instead, by the way.

**Comment by Akaricchi** [comment]
It seems like the cancellation effect also occurs if the shot button is pressed during transition, which is indeed rather annoying.
