### ISSUE TITLE
Change stage 3 kedamas that go top to bottom

### ISSUE THREAD

**Issue by ultroloth** [taisei-project/taisei#137]
Their aiming is random and doesn't help when trying to get a consistent route down for the stage, especially since they move from top to bottom, meaning that they shoot you from every angle on the side they're on. The ones in the post midboss section also awkwardly transition into the rest of the stage and I personally think having no filler kedamas would be best.

**Comment by Akaricchi** [comment]
Closing a bunch of issues as stale and/or no longer relevant; feel free to reopen as needed.
