### ISSUE TITLE
Taisei in Flatpak (via Flathub)

### ISSUE THREAD

**Issue by rrigby** [taisei-project/taisei#141]
Hi,
I've submitted a flatpak manifest for Taisei to flathub.
https://github.com/flatpak
https://github.com/flathub

If you're interested in maintaining the flatpak manifest feel free to comment here to get admin access to the repository.
https://github.com/flathub/flathub/pull/538

**Comment by laochailan** [comment]
Hi,

There has been some demand for a sandboxed version of Taisei, so I think this is cool! Sadly, we are a bit short on people and don’t really have experience with flatpak, so it would be very helpful if you could maintain this. If any issues turn up in future versions, we can help you debug. :)

**Comment by rrigby** [comment]
That's all good with me.

There's also an appdata.xml file in the PR that might interest you if you plan on packaging Taisei for inclusion on other software repos in the future.

Thanks again!

**Comment by laochailan** [comment]
I see, thanks!
