### ISSUE TITLE
Switch version doesn't works on newer firmwares.

### ISSUE THREAD

**Issue by Yoshideking** [taisei-project/taisei#218]
Hi,

since firmware 9.00 homebrew needs to be compiled for the latest library for 9.X.X or it doesn't detects the buttons of the Nintendo Switch.

Not quite sure what is the real problem, but I used this app now and then.

Thanks in advance.

**Comment by Akaricchi** [comment]
I have recompiled v1.3.1 against a newer libnx and updated [the release binary](https://github.com/taisei-project/taisei/releases/download/v1.3.1/Taisei-1.3.1-switch-aarch64.zip). It seems to be working for @p-sam, and he's going to get the homebrew store updated soon as well. Feel free to reopen the issue if any concerns remain.
