### ISSUE TITLE
Graphics look wrong

### ISSUE THREAD

**Issue by HybridDog** [taisei-project/taisei#224]
I don't know how to explain this. When I run the newest version (commit f7763fe), textures look wrong and I have a low framerate:
![a](https://user-images.githubusercontent.com/3192173/81505132-6fded380-92ed-11ea-9620-8a9a26f8185a.jpg)
![b](https://user-images.githubusercontent.com/3192173/81505141-740af100-92ed-11ea-85d0-6c6dacdd5ffc.jpg)
When the program is linked, there are many `-Wlto-type-mismatch` warnings (I don't know if this is related): https://pastebin.com/raw/zqTS2QGk
Here's the taisei output: https://pastebin.com/raw/MrLv6wWB

**Comment by Akaricchi** [comment]
The build warnings are interesting, but likely not relevant.

I assume from the log that the game used to work fine on this machine before. Do you remember what was the last working version? If you can [`git bisect`](https://git-scm.com/docs/git-bisect) the problem, that would be very helpful.

Please post the Taisei log file. It contains more information than the console output. It should be in `~/.local/share/taisei/log.txt` (assuming you're on Linux).

Also, make sure the game is properly installed and reads up to date resources - i.e. don't forget to run `ninja install` after building.

**Comment by HybridDog** [comment]
> Also, make sure the game is properly installed and reads up to date resources - i.e. don't forget to run ninja install after building.

This fixed the problem, thanks. 
I've executed `src/taisei` in the build folder to test if the game works before installing it because I had a working previous installation.
