### ISSUE TITLE
Unexpected death in Wriggle Night Ignite spell

### ISSUE THREAD

**Issue by HybridDog** [taisei-project/taisei#234]
When the player is on the bottom of the screen in the Wriggle Night Ignite spell, sometimes death happens even if the player touches nothing dangerous (I cannot see the reason for the death).
I don't know if this is supposed to happen, so I've opened this issue.

Screenshot just before the death:
![fot_2020-06-03-17:55:31_723311668](https://user-images.githubusercontent.com/3192173/83660024-975f4e00-a5c4-11ea-8189-3ea4b9fbef3d.jpg)
Video of the problem: https://sendvid.com/qlcea50q
Full taisei replay: [taisei_20200603_17-41-40-704_stg3_youmuB_easy.tsr.zip](https://github.com/taisei-project/taisei/files/4724613/taisei_20200603_17-41-40-704_stg3_youmuB_easy.tsr.zip)

Taisei version: v1.3-382-gb7233ce8-master release

**Comment by Akaricchi** [comment]
It's not supposed to happen. Not sure what is the cause yet, will investigate. Might be a subtle laser collision bug. Thanks for reporting.

By the way, there is no need to zip replays. They are already compressed.

**Comment by HybridDog** [comment]
> By the way, there is no need to zip replays. They are already compressed.

I know; unfortunately github does not allow arbitrary file extensions.

> Meanwhile, if you could reproduce this in spell practice (with a replay), that would be helpful as well.

Done: [replays.zip](https://github.com/taisei-project/taisei/files/4725151/replays.zip)
I could not reproduce it in hard mode.

**Comment by HybridDog** [comment]
I have noticed a similar problem in the Moonlight Rocket spell.
When the player is on the top left corner, death transpires. 
Here's a replay (with .txt suffix to fool the github file type restriction): [taisei_20200715_22-12-02-916_stg8309_youmuA_lunatic.tsr.txt](https://github.com/taisei-project/taisei/files/4927735/taisei_20200715_22-12-02-916_stg8309_youmuA_lunatic.tsr.txt)

**Comment by Akaricchi** [comment]
I've just pushed a fix to master; bogus deaths no longer occur in those two replays for me. Please reopen the issue if you encounter this problem again.

**Comment by HybridDog** [comment]
Thanks for the fix.
