### ISSUE TITLE
Spelling mistakes [meta]

### ISSUE THREAD

**Issue by StarWitch** [taisei-project/taisei#267]
For reporting any spelling/grammar mistakes in the current script.

### Intro
* `Outside the shrine, nearly every resident of Yōkai Mountain were lined up one after another to make a donation - including the Moriya Shrine Gods, Kanako and Suwako.`  ->  `Outside the shrine, nearly every resident of Yōkai Mountain was lined up one after another to make a donation - including the Moriya Shrine Gods, Kanako and Suwako.`
* `It would start with figuring out simple problems that they'd been struggling with, such as a technical issue with a machine or perhaps a eye-catching newspaper headline.`  ->  `It would start with figuring out simple problems that they'd been struggling with, such as a technical issue with a machine or perhaps an eye-catching newspaper headline.`

### Reimu
* Sanae repeats herself Good Ending
* Elly: `This will the sigil of a new era!` -> `This will *be* the sigil of a new era`
* `Everything else feels terrible again my skinー` -> `Everything else feels terrible against my skinー`
* Change to "cradled": `She didn't feel like drinking, however. She nursed it without even uncorking it, sighing to herself.`
* `The Tower had been shut down, ending the crisis of madness sweeping land.` -> `The Tower had been shut down, ending the crisis of madness sweeping the land.`

### Marisa
* Reword this: `Nothing will stand against our path of vengeance for those who have been forgotten by theー`
* `"I mean, 'course ya lost. Mathematics has always been linked with magic. Don't you know about Issac Newton?"`  =>  `"I mean, 'course ya lost. Mathematics has always had a soft spot for magic. Don't ya know about Isaac Newton?"
* `I'm sick of guarding this creepy spooky mansion anyways.`  =>  `I'm sick of guarding this creepy, spooky mansion anyways.`

### Youmu
* `It seems that the machine has also overinflated your ego, Swordswoman of the Hakugyokurō.`  ->  `It seems that the machine has also overinflated your ego, Swordswoman of Hakugyokurō.`
* Normalize the wording of this with other endings: `To unlock the Extra Stage, keep trying to reach the end without using a Continue!`

**Comment by Akaricchi** [comment]
Can you prepare a PR with these fixes? I see no point in accumulating them in this issue.
