### ISSUE TITLE
How to show fps?

### ISSUE THREAD

**Issue by l29ah** [taisei-project/taisei#314]
I see some mentions in the code, but i couldn't find it in the configuration dialogs.

**Comment by StarWitch** [comment]
Is the FPS counter not appearing for you in the main game, on the lower-right part of the screen?

See: 
<img width="220" alt="image" src="https://user-images.githubusercontent.com/34408664/126019861-30fa2be6-49be-41e0-8dc3-83f67ad47437.png">

**Comment by l29ah** [comment]
Oh, apparently it only appears during the actual game, and i was too distracted by the game itself to be able to see it :)
Thanks for the great game and sorry for the noise!

**Comment by StarWitch** [comment]
No worries, thanks for the report. Feel free to let us know if anything else comes up. 🙂
