### ISSUE TITLE
Talsei: fatal error

### ISSUE THREAD

**Issue by AnimeniacSimey** [taisei-project/taisei#340]
Get this when trying to open the game. Any tips? 

`FATAL  gl33_init_texunits: GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS is -1675742202; at least 4 is expected.`

**Comment by StarWitch** [comment]
If you're still experiencing this issue, feel free to re-open this ticket. As it's been a month since any feedback, closing for now.
