### ISSUE TITLE
Post-Dokomi 2023/v1.4 Gold Fixes/Tweaks

### ISSUE THREAD

**Issue by StarWitch** [taisei-project/taisei#368]
### Boss/Stage Pattern Changes
- [x] Redesign Wriggle's stage 3 fight — at least replace night ignite and firefly storm spells
- [ ] Redesign Vlad's army
- [x] Redesign Animate Wall
- [ ] Improve Iku's Overload (lock onto the target spot slightly before activating?)
- [x] Improve some poorly telegraphed sections in stage 4 (particularly the laser-fairy ring in second half)
- [x] Overall minor difficulty adjustments based on replay feedback

### Tweaks/Fixes
- [x] Scoring change: collect point items at full power while surging
- [x] Improve joystick handling (too sensitive in menus, radial deadzones)
- [x] Start tracking high-scores and stage/spell plays/clears per-character (internal only; full implementation in v1.5)
- [x] Fix double-transition from credits into main menu

### Maintenance
- [x] Update wrap dependencies to latest versions; make sure everything builds and runs on all supported platforms
- [x] Make high-score a 64bit int (because regular score is already one; this wasn't updated due to an oversight)
- [x] Update shipped demos so they don't desync after the new changes (some of them might only need to be `--rereplay`'d due to score divergence, others replaced)
- [x] Update game manual

**Comment by Akaricchi** [comment]
Most of this is done and v1.4 is out, so closing.
