### ISSUE TITLE
[minor] lost v from version number in file

### ISSUE THREAD

**Issue by ghost** [taisei-project/taisei#370]
the previous release had "v1.3.2" in the file name, now it's "1.4". This brakes  download scripts, you need to stay consistent. Now it's too late to fix it.

**Comment by Akaricchi** [comment]
Sorry about that. We switched to an automated release pipeline between v1.3.2 and v1.4, and I guess this change slipped through the cracks. You can expect to have no `v` in future releases from now on. I'll add a note to the release description.
