### ISSUE TITLE
Music clipping/distortion on Switch in version 1.4

### ISSUE THREAD

**Issue by TwistedTempest** [taisei-project/taisei#374]
Ever since the release of ver. 1.4, the music on the Switch NRO when launched from the homebrew menu has sounded slightly slowed and prone to clipping and distortion. This only affects the music, not the sound effects, which sound normal. It sounds like this:

https://github.com/taisei-project/taisei/assets/75958359/4837c1fc-707d-4860-b30d-63fd9f66a42d

**Comment by TwistedTempest** [comment]
Closing as found the solution in the game's Discord server

**Comment by StarWitch** [comment]
If you could, could you post what the solutions was here as well? Discord isn't a permanent resource and it'd be better to keep a record for those experiencing similar issues.

**Comment by TwistedTempest** [comment]
Upon updating the game, it seems that the developers switched audio libraries (or linkers? my understanding of the topic is pretty vague) to their own custom one, and the default mixer_chunksize value causes this issue on Switch. setting the mixer_chunksize value (stored at (SD):/switch/taisei/storage/config.txt) to 1024 fixes the audio as far as I can tell

> If you could, could you post what the solutions was here as well? Discord isn't a permanent resource and it'd be better to keep a record for those experiencing similar issues.

**Comment by Akaricchi** [comment]
@TwistedTempest Can you please try [this build](https://0x0.st/HIN7.zip/Taisei-1.4-42-g3054c331-v1.4.x-switch-aarch64.zip) with `mixer_chunksize = 512` in the config?

**Comment by TwistedTempest** [comment]
This build does not have the issue, thanks!

> @TwistedTempest Can you please try [this build](https://0x0.st/HIN7.zip/Taisei-1.4-42-g3054c331-v1.4.x-switch-aarch64.zip) with `mixer_chunksize = 512` in the config?
