### ISSUE TITLE
Voltage overdrive activates during stage clear screen

### ISSUE THREAD

**Issue by no-comma** [taisei-project/taisei#377]
In Taisei v1.4, if enough voltage is collected to unlock voltage overdrive right as a boss is defeated, the stage clear screen and the voltage overdrive will start at the same time.

[taisei.webm](https://github.com/taisei-project/taisei/assets/82644961/4f6b83d3-de77-46bf-b943-418bacb15a2e)

Full replay: 
[taisei_20240110_16-02-46-103_youmuA_normal.zip](https://github.com/taisei-project/taisei/files/13888966/taisei_20240110_16-02-46-103_youmuA_normal.zip)

**Comment by Akaricchi** [comment]
Thanks for the replay.

I'm not sure if this can be addressed in a v1.4.x patch without breaking replays, but I'll have this fixed by v1.5.
