### ISSUE TITLE
Build failure with cglm-0.9.3

### ISSUE THREAD

**Issue by olifre** [taisei-project/taisei#381]
Trying to build against `cglm-0.9.3`, I run into errors:
```
In file included from ../src/util/compat.h:13,
                 from ../src/taisei.h:13,
                 from ../src/boss.c:9:
../subprojects/cglm/include/cglm/vec2.h:725:23: error: expected ‘)’ before ‘__extension__’
  725 | glm_vec2_reflect(vec2 I, vec2 N, vec2 dest) {
      |                       ^
In file included from ../subprojects/cglm/include/cglm/cglm.h:12,
                 from ../src/util/glm.h:20,
                 from ../src/boss.c:17:
../subprojects/cglm/include/cglm/vec2.h:725:26: error: expected ‘;’, ‘,’ or ‘)’ before ‘vec2’
  725 | glm_vec2_reflect(vec2 I, vec2 N, vec2 dest) {
      |                          ^~~~
```
It seems the reflect functions were newly added to `0.9.3`.

**Comment by Akaricchi** [comment]
Bug in cglm. `I` is a standard C macro defined in `complex.h` (https://en.cppreference.com/w/c/numeric/complex) and must not be used as a variable name. Taisei uses complex math extensively, and therefore includes the `complex.h` header. Please report this upstream.

**Comment by olifre** [comment]
Thanks a lot, this explains it easily. Reported upstream as:
https://github.com/recp/cglm/issues/404

**Comment by recp** [comment]
Hi

I tried to fix this at https://github.com/recp/cglm/pull/406 and new Release will be soon. 

Thanks

**Comment by recp** [comment]
v0.9.4 of **cglm** is released: https://github.com/recp/cglm/releases and the issue is fixed 🚀

**Comment by olifre** [comment]
Many thanks again! Closing this bug then :+1: .
