### ISSUE TITLE
Strange bullet patterns

### ISSUE THREAD

**Issue by bergfried** [taisei-project/taisei#390]
Maybe it's just me but some of the bullet patterns I see just don't seem right. After the first encounter with Cirno in the first stage, some of those greenish enemies emit bullets in patterns that appear shifted around (e.g. bullets appear above the enemy and then cross the enemy downwards, essentially shooting the enemy itself) or even reversed (i.e. they shoot upward instead of downward).

Replay: [stg1_marisaA_normal.tsr.zip](https://github.com/user-attachments/files/17692258/stg1_marisaA_normal.tsr.zip)

Three notable cases from the replay (one case per row, time progresses from left to right):
![strangebulletpatterns](https://github.com/user-attachments/assets/9bb514f0-22ab-47cb-a753-dcc0c3cd1f9b)

Is this intended? Especially the first case (shooting upward) does not make sense to me at all.

**Comment by Akaricchi** [comment]
Works as intended.

**Comment by bergfried** [comment]
Thank you for the clarification.
