### ISSUE TITLE
how to enable the bundled SDL2's kmsdrm support?

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [taisei-project/taisei#392]
Firstly, I'm sorry to disturb you. 
Recently I'm trying to port this game to a Linux based game console, that console have no X server, and software need to display over DRM.
But I have few experience in using the meson build system, and I can't find a way to enable the DRM support of the bundled SDL2, or the way to dynamic link to the existed SDL2 object file, even after I read a lot of documents and manuals.

PLEASE HELP ME HOW TO DO THIS, Thanks.

**Comment by Akaricchi** [comment]
I'm assuming you're cross-compiling and the sysroot of your cross environment is in `/home/whatever/console`.

If you want to link to external SDL, you have to build and *install* it into that sysroot first. I can't tell you how to do that, sorry. SDL uses cmake, and cmake sucks ass. You'll have to figure that out on your own. In the best case, your build environment might provide a cmake wrapper that you can use and then just `make install` it. I'll just assume that this step is done already.

To cross-compile meson projects (such as Taisei), you have to specify the environment with a [meson cross file](https://mesonbuild.com/Cross-compilation.html). This is where you set up things such as the compiler and linker binaries, host CPU architecture, and among other things, these two important variables in the properties section:

```ini
[properties]
sys_root = '/home/whatever/console'
pkg_config_libdir = '/home/whatever/console/lib/pkgconfig'
```

`pkg_config_libdir` may vary, but it's usually `lib/pkgconfig` under the sysroot. For example, it's `/usr/lib64/pkgconfig` on my openSUSE Tumbleweed host system. If SDL is installed correctly, you should have a `sdl2.pc` file in there. That's how meson (and most build systems) usually finds dependencies.

**Comment by Dawn-Xu-helloworld** [comment]
does ARM's official build toolchains(https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads) support sysroot?
seems it doesn't work fine while linking to ld-linux-asrch64.so

**Comment by Dawn-Xu-helloworld** [comment]
Aha！ It works!!
Now I can play Taisei on my bed in dormitory
