### ISSUE TITLE
Enemy shot sounds

### ISSUE THREAD

**Issue by laochailan** [taisei-project/taisei#52]
In normal Touhou, every bullet has a sound, I think. Different sounds for different types of bullets and situations and bells for things like the particles changing state.

I could probably cheat together some sounds. The question is how to incorporate them into the game efficiently. Could we just add a play_sound to create_projectile without screwing things up? Do you have thoughts on this?

**Comment by Akaricchi** [comment]
>Could we just add a play_sound to create_projectile without screwing things up? Do you have thoughts on this?

It won't be that simple. First off, what are you going to base the decision of which exactly sound to play on? The projectile sprite? If so, I'm not sure that'd be appropriate in every situation -- sometimes you'll want to play a custom sound to alert of a special spellcard mechanic without having the generic bullet sounds get in your way. Another issue is that you can have *really* many create_projectile_p calls in one frame. You really don't want to play the same sound multiple times per frame -- it'll get distorted and loud, and you run the risk of running out of audio sources.

I don't have any better ideas than just inserting play_sound calls in enemy logic code whenever they shoot/something important happens. It is verbose, but flexible.

**Comment by Akaricchi** [comment]
Now that I think about it, maybe it will be better to have the "protected" play_sound called inside of create_projectile_p automatically after all, but add an easy and not hackish way to override that. I'm not sure exactly how. I really don't want to add yet another parameter to that function, I find myself grepping for its prototype often enough.

**Comment by lachs0r** [comment]
Sorry, I’m horribly unfamiliar with the code or how sound works in this game or how the OpenAL API works. But if that many sounds may be triggered on each frame, maybe a priority system/queue would work, with higher-priority sounds automatically attenuating or cancelling lower-priority ones? And deduplication of course.

In theory, we should also ensure that we don’t attempt to play more sounds at once than the OpenAL implementation allows, so, short of implementing our own mixing, this might be useful anyway…

**Comment by Akaricchi** [comment]
Oh I doubt there will be a lot of *different* sounds initiated in a single frame. But we have lots of cases where dozens of similar bullets are created in a loop (to form a circular pattern for example), and if they all trigger the same sound that'd be a problem. Deduplication should be enough to fix that.

**Comment by makise-homura** [comment]
As I remember from Touhou, there are single sound for every _simultaneously_ shot bunch of bullets: so, I think, the simpliest place where such sound should be generated is the enemy's attack.
But it means adding such code to stage mechanics which define enemies and their attacks, and that seems to be not a best place for it (every attack would have additional play_sound() call, mostly similar to many another calls). But we have an advantage comparing to next idea: we may use different sounds for attacks consisting of equal projectile types. But, seriously, do we really need this?..

As far as I know, OpenAL has no such integrated things as deduplication or some kind of priority system (as it may be expected though).
But we can do it ourselves! For example, in-stage play_sound() (`unconditional == false`) may only _shedule_ sound that will start playing in next frame, and we may have some kind of "sound deduplicator" that will be called every frame and play only one sheduled sound of the same name. So even if enemy generates over 9000 projectiles, only one sound will be played - but it will not be masked by or stop similar sound that started playing a bit before (so no sound loss will occur).

It looks like too complicated, but I see no way that is simplier.

**Comment by laochailan** [comment]
My idea would be to just put some kind of lock into the sound structure, maybe a time stamp. Then only play the next sound when the time is time stamp + sound duration or later.

**Comment by laochailan** [comment]
We are already doing that by the way, right? There are no duplicate sounds in the same frame except they get called with `uncoditional == true`.

**Comment by makise-homura** [comment]
As I noticed from the [documentation of SDL2_mixer](https://www.libsdl.org/projects/SDL_mixer/), "It supports any number of simultaneously playing channels of 16 bit stereo audio", so we have no reason to worry about number of playing sounds. Only problem that may occur is unnatural amplification of sounds started at the same time, if their mixing is dumb and not relied on complicated physics like modeling of air medium which is overkill for us, of course. So we shall see: I think, at first we only should cancel similar sounds initiated in the same frame.

>Then only play the next sound when the time is time stamp + sound duration or later.

It may result in loss of repeatable sounds. According to shot sounds that typically have strong attack and decay and maybe prolonged aftersound (sustain-release) greater than shooting interval, I think we can "rewind" sound and play it from the beginning in such cases, and it will be indistinguishable from the situations where every sound plays to end. Sounds like charging that do not have strong attack and decay don't fit these criteria, but may be rewinded or played simultaneously by some decision.
But, at first, I think we may listen how does it sound if we don't use any specific algorithms except for cancelling sounds started at the same time - and then fix problems if they arise with this.

>We are already doing that in a way, right?

Oh, really it is! I just was somewhat confused with `lastplayframe` variable name and misunderstood its meaning. That's really the same thing I've talked about.

**Comment by laochailan** [comment]
I can try to do some test shooting sound then and we can look what it sounds like if we add it to create_projectile. Maybe `lastplayframe` is a confusing name. Do you have an idea for a better one? Then again it’s holding a frame number so I would keep the `frame` in there. Some comments may be in order though.

**Comment by makise-homura** [comment]
>Do you have an idea for a better one?
Looks like there is no definitely clear and self-documenting name for such thing. Maybe `startplayframe` or even `startingframe` appears to be more suiltable for me, but not very significantly.

**Comment by laochailan** [comment]
I’ve tried to introduce shot sounds. But it really difficult to make a shot sound that doesn’t sound obnoxious when repeated a lot.

**Comment by makise-homura** [comment]
> it really difficult to make a shot sound that doesn’t sound obnoxious when repeated a lot.
Yes, it's really hard, but for a first approach, I may notice that it sounds more pretty if sound has slight attack and not very sharp attack-decay peak; for example, player shot and boss hit sounds from Touhou conforms to this rule. Maybe it would be good for massively repeatable enemy shot sounds too.

**Comment by laochailan** [comment]
Okay, I don’t know very much about sounds. I’ve also noticed that if the decay is too slow, the clipping gets worse because more sounds get played at a time.

**Comment by laochailan** [comment]
We kind of got around this for now.
