### ISSUE TITLE
Missing Resources

### ISSUE THREAD

**Issue by laochailan** [taisei-project/taisei#76]
This is just an issue to keep track of the resources we are missing.

### BGM

- [x] Stage 1
- [x] Stage 1 Boss
- [x] Stage 2
- [x] Stage 2 Boss
- [x] Stage 3
- [x] Stage 3 Boss
- [x] Stage 4
- [x] Stage 4 Boss
- [x] Stage 5
- [x] Stage 5 Boss
- [x] Stage 6
- [x] Stage 6 Boss
- [x] Menu
- [x] Credits
- [x] Ending
- [ ] Gameover (not sure if needed, so this is lower priority than everything else)

### SFX

- [x] Most urgently we need a sound for enemy shots. Cool charge up sounds and chimes would also be cool for some attacks. (#52)
- [x] Power up sound
- [x] Extra life sound
- [x] Extra bomb sound

### GFX

- [ ] Some pictures for the different endings. I can do them when I get motivation.

**Comment by Akaricchi** [comment]
Closing a bunch of issues as stale and/or no longer relevant; feel free to reopen as needed.
