### ISSUE TITLE
Issue with the AppImage in Ubuntu 17.10

### ISSUE THREAD

**Issue by Mister-Dolus** [taisei-project/taisei#92]
Trying to run the AppImage in 64-bit 17.10 gets me the following error: 

"$ ./taisei-1.1+195.g1a45593-Build228.1.glibc2.14-x86_64.AppImage 
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
do_winsys_init: DRM version is 3.18.0 but this driver is only compatible with 2.12.0 (kernel 3.2) or later.
1076      W: load_resource(): Failed to locate bgm 'menu'
1076      W: parse_keyvalue_file_cb(): VFS error: Node 'res/shader/postprocess.conf' does not exist
1076      W: progress_load(): Couldn't open the progress file: SDL error: Couldn't open /home/desum/.local/share/taisei/progress.dat
1085      W: get_resource(): bgm 'menu' was not preloaded
1085      W: load_resource(): Failed to locate bgm 'menu'
1085      W: start_bgm(): BGM 'menu' does not exist"

Happens with or without the Padoka PPA. Worst bit is that all eight of my CPU cores shoot up to 100% and the only fix is a reboot

**Comment by Mister-Dolus** [comment]
Hardware:
AMD FX 8350
RX 480 with Mesa

OS: 
Ubuntu Mate 17.10 AMD64

**Comment by lachs0r** [comment]
```
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
do_winsys_init: DRM version is 3.18.0 but this driver is only compatible with 2.12.0 (kernel 3.2) or later.
```

That is almost guaranteed to be a driver issue.

**Comment by Akaricchi** [comment]
Does OpenGL work at all? Try glxgears, glxinfo, or another GL-based game maybe.

**Comment by lachs0r** [comment]
Maybe this is some Wayland issue? Does Ubuntu MATE also use Wayland by default?
I could imagine something like SDL trying to use the DRM backend because Wayland failed…

**Comment by lachs0r** [comment]
https://www.reddit.com/r/linux/comments/4jc6zh/amd_unleashes_initial_amdgpu_driver_support_for/d35sohx/

So yeah, this looks like Ubuntu MATE ships with a broken driver setup (wouldn’t put it past them), unless you’ve done and ruined it yourself.

**Comment by Mister-Dolus** [comment]
>driver issue
Doesn't seem to be the case, OpenGL works fine. And this happens with both the default Mesa drivers and the Padoka PPA. Pretty much every Steam game works for me too. 

I tried the .deb installer and that works too with no error other than the missing bgm (which I assume hasn't been added yet):

desum@desum-MS-7992:~/Desktop$ taisei
315       W: load_resource(): Failed to locate bgm 'menu'
315       W: parse_keyvalue_file_cb(): VFS error: Node 'res/shader/postprocess.conf' does not exist
315       W: get_resource(): bgm 'menu' was not preloaded
315       W: load_resource(): Failed to locate bgm 'menu'
315       W: start_bgm(): BGM 'menu' does not exist

**Comment by Mister-Dolus** [comment]
As far as I know, other than the GTK3 port, no real work on Mate/Wayland has happened yet.

**Comment by Mister-Dolus** [comment]
Just tried the AppImage in Manjaro on the same box and I get the same error: 
[manjaro@manjaro-mate Downloads]$ ./taisei-1.1+198.gcdb621e-Build230.1.glibc2.14-x86_64.AppImage 
amdgpu: amdgpu_device_initialize failed.
do_winsys_init: DRM version is 3.8.0 but this driver is only compatible with 2.12.0 (kernel 3.2) or later.
2807      W: load_resource(): Failed to locate bgm 'menu'
2815      W: parse_keyvalue_file_cb(): VFS error: Node 'res/shader/postprocess.conf' does not exist
2816      W: progress_load(): Couldn't open the progress file: SDL error: Couldn't open /home/manjaro/.local/share/taisei/progress.dat
2817      W: get_resource(): bgm 'menu' was not preloaded
2818      W: load_resource(): Failed to locate bgm 'menu'
2818      W: start_bgm(): BGM 'menu' does not exist

**Comment by Mister-Dolus** [comment]
I also tested the version from the AUR, and that worked fine.

**Comment by dino99** [comment]
with one of my appimage app, i've found that it need libgconf to get it loaded.

**Comment by laochailan** [comment]
With AppImage being so strange and that GL problem being only specific to AppImage, we decided to drop it and just supply statically linked binaries as a “portable across linux” thing in the future. Much more predictable and probably less effort to get right.

Thanks for your effort @Mister-Dolus and @dino99 though :)

**Comment by lachs0r** [comment]
Building proper packages for half a dozen distros and their various releases is in fact much easier than producing a single working bundle. So we’re doing just that (to the extent possible with OBS).

It’s a little counter-intuitive because not having to do this is one of the major selling points for all those app bundle techniques. Guess they’re just another solution looking for a problem, and about as well-engineered as you’d expect from people with a background in web and/or Windows development.
