### ISSUE TITLE
Audio support regression on Manjaro/Arch

### ISSUE THREAD

**Issue by pzmarzly** [taisei-project/taisei#94]
Audio works for me only on taisei-1.1+199.ga6a1660-Build231.1.glibc2.14-x86_64.AppImage. Log:

    i965_dri.so does not support the 0xffffffff PCI ID.
    958       W: load_resource(): Failed to locate bgm 'menu'
    960       W: parse_keyvalue_file_cb(): VFS error: Node 'res/shader/postprocess.conf' does not exist
    960       W: progress_read(): Progress file will be automatically downgraded from v1.1.1 to v1.1.0.199 
    upon saving
    968       W: get_resource(): bgm 'menu' was not preloaded
    969       W: load_resource(): Failed to locate bgm 'menu'
    969       W: start_bgm(): BGM 'menu' does not exist

It doesn't on AUR taisei ver. 1.1.1-1. Log:

    0         W: config_set(): Unknown setting 'key_fpslimit_off'
    90        W: png_warning_handler(): PNG warning: iCCP: known incorrect sRGB profile
    184       W: load_resource(): Failed to locate bgm 'bgm_menu'
    184       W: parse_keyvalue_file_cb(): VFS error: Node 'res/shader/postprocess.conf' does not exist
    184       W: progress_read(): Unknown command 5 (3 bytes). Will preserve as-is and not interpret.
    184       W: get_resource(): bgm 'bgm_menu' was not preloaded
    184       W: load_resource(): Failed to locate bgm 'bgm_menu'
    184       W: start_bgm(): BGM 'bgm_menu' does not exist
    194       W: load_sound_begin(): Mix_LoadWAV() failed: Audio device hasn't been opened
    194       W: load_resource_finish(): Failed to load sound 'generic_shot' (res/sfx/generic_shot.wav)
    196       W: load_sound_begin(): Mix_LoadWAV() failed: Audio device hasn't been opened
    197       W: load_resource_finish(): Failed to load sound 'hit' (res/sfx/hit.wav)
    198       W: load_sound_begin(): Mix_LoadWAV() failed: Audio device hasn't been opened
    198       W: load_resource_finish(): Failed to load sound 'shot_special1' (res/sfx/shot_special1.wav)

It also doesn't work on AUR taisei-git ver. 1.1.r237.gfc57c9f-1, log:

    482       W: audio_backend_init(): Mix_Init() failed: OGG support not available
    559       W: load_resource(): Failed to locate bgm 'menu'
    560       W: parse_keyvalue_file_cb(): VFS error: Node 'res/shader/postprocess.conf' does not exist
    560       W: get_resource(): bgm 'menu' was not preloaded
    560       W: load_resource(): Failed to locate bgm 'menu'
    560       W: start_bgm(): BGM 'menu' does not exist
    567       W: load_sound_begin(): Mix_LoadWAV_RW() failed: Audio device hasn't been opened
    567       W: load_resource_finish(): Failed to load sound 'generic_shot' (res/sfx/generic_shot.ogg)
    572       W: load_sound_begin(): Mix_LoadWAV_RW() failed: Audio device hasn't been opened
    572       W: load_resource_finish(): Failed to load sound 'shot_special1' (res/sfx/shot_special1.ogg)
    574       W: load_sound_begin(): Mix_LoadWAV_RW() failed: Audio device hasn't been opened
    574       W: load_resource_finish(): Failed to load sound 'hit' (res/sfx/hit.ogg)

I tried all versions with the same ~/.local/share/taisei folder, then removed it before launching each version, it changed nothing.

It happens both with headphones plugged and unplugged. I'm using Manjaro's default pulseaudio and alsa configuration (pulseaudio sink is the default alsa device). I have ALC223 soundcard, detected as HDA Intel PCH.

Thanks in advance for any help with this issue.

**Comment by Akaricchi** [comment]
This is a bug in SDL_mixer 2.0.2: https://bugzilla.libsdl.org/show_bug.cgi?id=3929

It's quite outrageous that this still hasn't been patched. Don't use the AppImage, it bundles all the dependencies. Downgrade `sdl2_mixer` to 2.0.1 or install [`sdl2_mixer-hg`](https://aur.archlinux.org/packages/sdl2_mixer-hg) from AUR. Then either install Taisei from AUR ([`taisei-git`](https://aur.archlinux.org/packages/taisei-git/)), or from our OBS repository (add this to your pacman.conf):

```ini
[taisei_dev]
Server = https://download.opensuse.org/repositories/home:/lachs0r:/taisei/Arch_Extra/$arch
```

See if that fixes the problem for you.

Also, as far as I know, @lachs0r has suspended the AppImage builds for now, and we may not support them at all in the future.

**Comment by Akaricchi** [comment]
For the record, I just filed a bug about it to Arch: https://bugs.archlinux.org/task/56303

**Comment by pzmarzly** [comment]
Thanks for quick reply.

First of all, I have noticed there is no such repo as taisei_dev - on https://download.opensuse.org/repositories/home:/lachs0r:/taisei/ there are no builds for Arch (there still are stable builds on https://download.opensuse.org/repositories/home:/lachs0r:/taisei:/stable/Arch_Extra/ though).

Installing sdl2_mixer-hg fixes the issue, thanks for helping me.

**Comment by lachs0r** [comment]
Oops, I had accidentally disabled publishing on the dev repo. Fixed.
